#!/usr/bin/env python3

import os
import re
import sys
import json
import argparse
import textwrap
import requests

# Defaults
TEMPLATE_PLUGINC = textwrap.dedent('''
    #include "ewwii.h"

    RawMetadata plugin_metadata(void) {{
        RawMetadata info;
        info.id = "{plugin_name}";
        info.version = "1.0.0";
        return info;
    }}

    void plugin_init(const struct HostHandle *host) {{
        ewwii_log(host, "Hello from C!");
    }}

''').strip()

DEFAULT_MAKEFILE = textwrap.dedent('''
    CC = gcc
    CFLAGS = -fPIC -Wall -I bindings
    LDFLAGS = -shared -ldl -lm -lrt

    PLUGIN_OUT = lib{plugin_name}.so
    RUST_BRIDGE = bindings/libpluginc_ewwii.a
    SOURCES = $(wildcard src/*.c)

    all: $(PLUGIN_OUT)

    $(PLUGIN_OUT): $(SOURCES)
    \t$(CC) $(CFLAGS) -o $@ $^ $(RUST_BRIDGE) $(LDFLAGS)
    \tstrip --strip-all $@

    clean:
    \trm $(PLUGIN_OUT)

    .PHONY: all clean

''').strip()

DEFAULT_GITIGNORE = """bindings/
*.so
"""

def sanitize_name(value):
    sanitized = re.sub(r'[^a-zA-Z_-]', '', value)
    
    if not sanitized:
        raise argparse.ArgumentTypeError(f"Name '{value}' is invalid. It must contain only letters.")
    return sanitized

def write_file(path, content):
    """Helper to write content to a path, ensuring parent dirs exist."""
    dir_name = os.path.dirname(path)
    if dir_name:
        os.makedirs(dir_name, exist_ok=True)
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def download_assets(owner, repo, version):
    target_dir = "bindings"
    os.makedirs(target_dir, exist_ok=True)
    
    required_files = ["ewwii.h", "libpluginc_ewwii.a"]
    
    for name in required_files:
        download_url = f"https://github.com/{owner}/{repo}/releases/{version}/download/{name}"
        print(f"Downloading {name}...")
        
        try:
            with requests.get(download_url, stream=True) as r:
                if r.status_code == 404:
                    print(f"Error: {name} not found in the {version} release. Check the file name case/spelling.")
                    continue
                r.raise_for_status()
                
                with open(os.path.join(target_dir, name), "wb") as f:
                    for chunk in r.iter_content(chunk_size=8192):
                        f.write(chunk)
            print(f"Successfully saved {name}")
            
        except Exception as e:
            print(f"Failed to download {name}: {e}")

def list_release_index(owner, repo):
    file = "release-index.json"
    index = f"https://github.com/{owner}/{repo}/raw/refs/heads/main/.github/{file}"

    try:
        r = requests.get(index)
        r.raise_for_status() 
        
        release_index = r.json()
        for release, ewwii_ver in release_index.items():
            print(f"Release: {release} => ewwii: {ewwii_ver}")
            
        return release_index
    except Exception as e:
        print(f"Failed to fetch release index: {e}")

def main():
    parser = argparse.ArgumentParser(description="plugc-ewwii CLI")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    cwd = os.getcwd()
    current_dir_name = os.path.basename(cwd)
    default_name = re.sub(r'[^a-zA-Z_-]', '', current_dir_name)

    init_parser = subparsers.add_parser("init", help="Initialize the tool")
    init_parser.add_argument(
        "--name", 
        type=sanitize_name, 
        help="Optional name for initialization",
        default=default_name or "default-plug"
    )
    use_parser = subparsers.add_parser("use", help="Use bindings of the provided version")
    use_parser.add_argument(
        "version", 
        nargs="?",
        default="latest", 
        help="The version to use"
    )
    subparsers.add_parser("list", help="List all bindings and ewwii version compatibility")

    args = parser.parse_args()

    OWNER = "Byson94"
    REPO = "plug-in-c.ewwii"

    if args.command == "init":
        if len(os.listdir(os.getcwd())) != 0:
            print("Refusing to work on non-empty directory.")
            sys.exit(1)

        c_code = TEMPLATE_PLUGINC.format(plugin_name=args.name)
        makefile_content = DEFAULT_MAKEFILE.format(plugin_name=args.name).replace('\\t', '\t')
        
        print("Initializing local files...")
        write_file("src/plugin.c", c_code)
        write_file("Makefile", makefile_content)
        write_file(".gitignore", DEFAULT_GITIGNORE)

        print("Downloading bindings...")
        download_assets("Byson94", "plug-in-c.ewwii", "latest");
        
        print(f"Initialized '{args.name}' in current directory.")
    elif args.command == "use":
        print("Downloading bindings...")
        download_assets(OWNER, REPO, args.version);
    elif args.command == "list":
        list_release_index(OWNER, REPO)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
