name: Deploy Documentation

on:
  push:
    branches:
      - main # Change to master if needed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install MkDocs and Plugins
        run: |
          pip install mkdocs mkdocs-material

      - name: Generate Doxygen Configuration and Docs
        run: |
          printf "INPUT=ewwii.h\nOPTIMIZE_OUTPUT_FOR_C=YES\nGENERATE_HTML=YES\nGENERATE_LATEX=NO\nHTML_OUTPUT=doxygen_out" | doxygen -

      - name: Build MkDocs Site
        run: |
          mkdocs build

      - name: Integrate Doxygen into MkDocs Build
        run: |
          mkdir -p site/doxygen
          cp -r doxygen_out/* site/doxygen/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
